packages:
  - apps/**
  - packages/**

injectWorkspacePackages: true

forceLegacyDeploy: true

syncInjectedDepsAfterScripts:
  - build

strictDepBuilds: false

allowBuilds:
  '@nestjs/core': false
  '@parcel/watcher': false
  '@scarf/scarf': false
  '@swc/core': false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
