packages:
  - apps/**
  - packages/**

injectWorkspacePackages: true

forceLegacyDeploy: true

syncInjectedDepsAfterScripts:
  - build

allowBuilds:
  '@nestjs/core': set this to true or false
  '@scarf/scarf': set this to true or false
