project:
  name: Hetzner Cloud 
  description: |
    This project deploys a K8s cluster to Hetzner as an alternative to EKS so that other apps in this monorepo
    can be deployed.

  maintainers:
    - Robert Kwami

tags: [Root, Hcloud]

stack: infrastructure

tasks:
  init:
    command: 'tofu init'
    toolchain: 'system'

  plan:
    command: 'tofu plan'
    args: '-out outputs/tfplan'
    toolchain: 'system'
    deps: ['~:init']
    outputs: ['outputs/tfplan']
    options:
      cache: false

  deploy:
    command: 'tofu apply outputs/tfplan'
    toolchain: 'system'
    deps: ['~:plan']
    inputs: ['outputs/tfplan']
    options:
      cache: false

  clean:
    command: tofu state rm 'module.kubernetes.talos_machine_secrets.this'
    toolchain: 'system'
    deps: ['~:init']

  destroy:
    command: 'tofu destroy'
    args: '--auto-approve'
    toolchain: 'system'
    deps: ['~:init', 'clean']
    options:
      cache: false