project:
  name: EKS 
  description: |
    This project deploys an EKS cluster to AWS so that other apps in this monorepo
    can be deployed.

  maintainers:
    - Robert Kwami

tags: [Root, EKS]

stack: infrastructure

tasks:
  init:
    command: 'tofu init'
    toolchain: 'system'

  plan:
    command: 'tofu plan'
    args: '-out .plans/tfplan'
    toolchain: 'system'
    deps: ['~:init']
    outputs: ['.plans/tfplan']

  deploy:
    command: 'tofu apply .plans/tfplan'
    toolchain: 'system'
    deps: ['~:plan']
    inputs: ['.plans/tfplan']

  destroy:
    command: 'tofu destroy'
    args: '--auto-approve'
    toolchain: 'system'
    deps: ['~:init']