# YAML anchor to prevent repetition in victoria metrics chart
.monitoring-scheduling: &monitoring-scheduling
  nodeSelector:
    niovial.io/node-purpose: monitoring
  tolerations:
    - key: niovial.io/node-purpose
      operator: Equal
      value: monitoring
      effect: NoSchedule

globals:
  destinationServer: https://kubernetes.default.svc
  clusterName: portfolio-eks-cluster

system:
  karpenter-crd:
    chart: karpenter
    repoURL: oci://public.ecr.aws/karpenter/karpenter-crd
    targetRevision: 1.11.1
    namespace: kube-system
    syncWave: "-2"

  gateway-api-crds:
    repoURL: https://github.com/kubernetes-sigs/gateway-api
    path: config/crd/experimental
    targetRevision: v1.5.1
    namespace: "kube-system"
    syncWave: "-2"
  
  karpenter:
    chart: karpenter
    repoURL: oci://public.ecr.aws/karpenter/karpenter
    targetRevision: 1.11.1
    namespace: kube-system
    syncWave: "-1"
    values:
      settings:
        clusterName: portfolio-eks-cluster
        interruptionQueue: KarpenterInterruptionQueue-portfolio-eks-cluster
      serviceAccount:
        name: "karpenter"
      nodeSelector:
        niovial.io/node-purpose: system

  ebs-csi-driver:
    chart: aws-ebs-csi-driver
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    targetRevision: 2.60.0
    namespace: kube-system
    syncWave: "-1"
    values:
      controller:
        nodeSelector:
          niovial.io/node-purpose: system

  cnpg:
    chart: cloudnative-pg
    repoURL: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
    targetRevision: 0.28.2
    namespace: cnpg-system
    syncWave: "-1"
    values:
      nodeSelector:
        niovial.io/node-purpose: system
      tolerations:
        - key: CriticalAddonsOnly
          operator: Equal
          value: "true"
          effect: NoSchedule

  keda:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.19.0
    namespace: keda
    syncWave: "-1"
    values:
      nodeSelector:
        niovial.io/node-purpose: system
      tolerations:
        - key: CriticalAddonsOnly
          operator: Equal
          value: "true"
          effect: NoSchedule

  cluster-config:
    repoURL: https://github.com/rtnkwami/portfolio.git
    path: k8s/eks/gitops/config
    targetRevision: HEAD
    namespace: "kube-system"
    syncWave: "0"

  victoria-metrics-k8s-stack:
    chart: victoria-metrics-k8s-stack
    repoURL: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
    targetRevision: 0.78.0
    namespace: monitoring
    syncWave: "1"
    values:
      kube-state-metrics:
        <<: *monitoring-scheduling
      grafana:
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
        <<: *monitoring-scheduling
      victoria-metrics-operator:
        nodeSelector:
          niovial.io/node-purpose: system
        tolerations:
          - key: CriticalAddonsOnly
            operator: Equal
            value: "true"
            effect: NoSchedule
      alertmanager:
        spec:
          <<: *monitoring-scheduling
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
      vmsingle:
        spec:
          <<: *monitoring-scheduling
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
      vmalert:
        spec:
          <<: *monitoring-scheduling
      vmagent:
        spec:
          <<: *monitoring-scheduling
    syncOptions:
      - RespectIgnoreDifferences=true
    ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jqPathExpressions:
          - .webhooks[]?.clientConfig.caBundle
      - kind: Secret
        jsonPointers:
          - /data/admin-password
      - group: ""
        kind: Secret
        name: validation
        namespace: monitoring
        jsonPointers:
          - /data
      - group: apps
        kind: Deployment
        jsonPointers:
          - /spec/template/metadata/annotations/checksum~1secret

  atelier:
    repoURL: https://github.com/rtnkwami/portfolio.git
    path: apps/atelier/k8s
    targetRevision: HEAD
    namespace: atelier
    syncWave: "1"