globals:
  destinationServer: https://kubernetes.default.svc
  clusterName: portfolio-eks-cluster

system:
  victoria-metrics-k8s-stack:
    chart: victoria-metrics-k8s-stack
    repoURL: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
    targetRevision: 0.78.0
    namespace: monitoring
    syncWave: "1"
    syncOptions:
      - RespectIgnoreDifferences=true
    ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jqPathExpressions:
          - .webhooks[]?.clientConfig.caBundle
      - kind: Secret
        jsonPointers:
          - /data/admin-password
      - group: ""
        kind: Secret
        name: validation
        namespace: monitoring
        jsonPointers:
          - /data
      - group: apps
        kind: Deployment
        jsonPointers:
          - /spec/template/metadata/annotations/checksum~1secret