apiVersion: apps/v1
kind: Deployment
metadata:
  name: atelier-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: atelier
        image: rtnkwami/atelier-backend
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - name: backend
          containerPort: 3000
