apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: atelier-db
  labels:
    app.kubernetes.io/name: atelier
    app.kubernetes.io/component: database
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 3
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  storage:
    storageClass: database
    size: "20Gi"
  postgresql:
    synchronous:
      method: any
      number: 1
      dataDurability: required
    parameters:
      shared_buffers: "512MB"
  affinity:
    nodeSelector:
      niovial.io/node-purpose: database
    enablePodAntiAffinity: true
    topologyKey: topology.kubernetes.io/zone
    podAntiAffinityType: required
    tolerations:
      - key: niovial.io/node-purpose
        operator: Equal
        value: database
        effect: NoSchedule