apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/rtnkwami/portfolio.git
    targetRevision: HEAD
    path: k8s/gitops/blueprint
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true