openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - App
  /inventory/categories:
    post:
      operationId: createCategory
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse_Output'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDto'
      summary: ''
      tags:
        - Inventory
    get:
      operationId: getAllCategories
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAllCategoriesResponse_Output'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDto'
      summary: ''
      tags:
        - Inventory
  /inventory/categories/{id}:
    patch:
      operationId: updateCategory
      parameters:
        - name: id
          required: true
          in: path
          schema:
            format: uuid
            pattern: >-
              ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCategoryDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse_Output'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDto'
      summary: ''
      tags:
        - Inventory
    get:
      operationId: getCategory
      parameters:
        - name: id
          required: true
          in: path
          schema:
            format: uuid
            pattern: >-
              ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse_Output'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardErrorDto'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDto'
      summary: ''
      tags:
        - Inventory
    delete:
      operationId: deleteCategory
      parameters:
        - name: id
          required: true
          in: path
          schema:
            format: uuid
            pattern: >-
              ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse_Output'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardErrorDto'
        '409':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardErrorDto'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDto'
      summary: ''
      tags:
        - Inventory
  /inventory/products:
    post:
      operationId: createProduct
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateProduct_Output'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardErrorDto'
        '409':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardErrorDto'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDto'
      summary: ''
      tags:
        - Inventory
    get:
      operationId: searchProducts
      parameters:
        - name: name
          required: false
          in: query
          schema:
            type: string
        - name: minPrice
          required: false
          in: query
          schema:
            minimum: 1
            type: number
        - name: maxPrice
          required: false
          in: query
          schema:
            minimum: 1
            type: number
        - name: category
          required: false
          in: query
          schema:
            format: uuid
            pattern: >-
              ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
            type: string
        - name: page
          required: false
          in: query
          schema:
            minimum: 1
            maximum: 9007199254740991
            type: integer
        - name: limit
          required: false
          in: query
          schema:
            minimum: 1
            maximum: 9007199254740991
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductSearchResults_Output'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardErrorDto'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDto'
      summary: ''
      tags:
        - Inventory
  /inventory/products/{id}:
    patch:
      operationId: updateProduct
      parameters:
        - name: id
          required: true
          in: path
          schema:
            format: uuid
            pattern: >-
              ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateProduct_Output'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardErrorDto'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardErrorDto'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDto'
      summary: ''
      tags:
        - Inventory
    get:
      operationId: getProduct
      parameters:
        - name: id
          required: true
          in: path
          schema:
            format: uuid
            pattern: >-
              ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateProduct_Output'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardErrorDto'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDto'
      summary: ''
      tags:
        - Inventory
info:
  title: Atelier Main API
  description: ''
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    InternalServerErrorDto:
      type: object
      properties:
        statusCode:
          type: number
        message:
          type: string
      required:
        - statusCode
        - message
    CreateCategoryDto:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    CategoryResponse_Output:
      type: object
      properties:
        id:
          type: string
          format: uuid
          pattern: >-
            ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
        name:
          type: string
      required:
        - id
        - name
      additionalProperties: false
    UpdateCategoryDto:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    getAllCategoriesResponse_Output:
      type: object
      properties:
        categories:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
                pattern: >-
                  ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
              name:
                type: string
            required:
              - id
              - name
            additionalProperties: false
      required:
        - categories
      additionalProperties: false
    StandardErrorDto:
      type: object
      properties:
        error:
          type: string
        statusCode:
          type: number
        message:
          type: string
      required:
        - error
        - statusCode
        - message
    CreateProductDto:
      type: object
      properties:
        product:
          type: object
          properties:
            name:
              type: string
              minLength: 1
            description:
              type: string
            price:
              type: number
              exclusiveMinimum: 0
            stock:
              type: number
              exclusiveMinimum: 0
          required:
            - name
            - price
            - stock
        category_id:
          type: string
          format: uuid
          pattern: >-
            ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
      required:
        - product
        - category_id
    PrivateProduct_Output:
      type: object
      properties:
        id:
          type: string
          format: uuid
          pattern: >-
            ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
        name:
          type: string
          minLength: 1
        description:
          type: string
        price:
          type: number
          minimum: 1
        category:
          type: string
          minLength: 1
        stock:
          type: integer
          minimum: 0
          maximum: 9007199254740991
        images:
          type: array
          default: []
          items:
            type: string
            minLength: 1
            format: uri
      required:
        - id
        - name
        - price
        - category
        - stock
        - images
      additionalProperties: false
    UpdateProductDto:
      type: object
      properties:
        product:
          type: object
          properties:
            name:
              type: string
              minLength: 1
            description:
              type: string
            price:
              type: number
              exclusiveMinimum: 0
            stock:
              type: number
              exclusiveMinimum: 0
          required:
            - name
            - price
            - stock
        category_id:
          type: string
          format: uuid
          pattern: >-
            ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
    ProductSearchResults_Output:
      type: object
      properties:
        products:
          type: array
          default: []
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
                pattern: >-
                  ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
              name:
                type: string
                minLength: 1
              description:
                type: string
              price:
                type: number
                minimum: 1
              category:
                type: string
                minLength: 1
              images:
                default: []
                type: array
                items:
                  type: string
                  minLength: 1
                  format: uri
            required:
              - id
              - name
              - price
              - category
              - images
            additionalProperties: false
        page:
          type: integer
          minimum: 1
          maximum: 9007199254740991
        perPage:
          type: integer
          minimum: 1
          maximum: 9007199254740991
        total:
          type: integer
          minimum: 0
          maximum: 9007199254740991
        totalPages:
          type: integer
          minimum: 1
          maximum: 9007199254740991
      required:
        - products
        - page
        - perPage
        - total
        - totalPages
      additionalProperties: false
    ValidationErrorDto:
      type: object
      properties:
        statusCode:
          type: number
        error:
          type: string
        errors:
          type: array
          items:
            type: object
      required:
        - statusCode
        - error
        - errors
