FROM node:24 AS base

WORKDIR /app

# Setup pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV MOON_TOOLCHAIN_FORCE_GLOBALS=true
RUN corepack enable

RUN pnpm install -g @moonrepo/cli

COPY ./.moon/docker/configs ./

RUN moon docker setup

COPY ./.moon/docker/sources ./

RUN moon run {{ project }}:build

{%- set parts = project | split(pat="/") -%}
{%- if parts | length > 1 -%}
  {%- set packageName = "@" ~ project -%}
{%- else -%}
  {%- set packageName = project -%}
{% endif %}

RUN pnpm deploy --filter={{ packageName }} --prod /prod/{{ project }}

FROM node:24-alpine

WORKDIR /app

RUN adduser -D -H service

COPY --chown=service:service --from=base /prod/{{ project }}/node_modules ./node_modules
COPY --chown=service:service --from=base /prod/{{ project }}/dist ./dist

USER service

# entrypoint of the container. Change to whatever suites the app
CMD ["node", "dist/main.js"]
