name: CI Pipeline
run-name: "CI Run for change: ${{ github.event.head_commit.message }}"

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - uses: actions/cache@v5
        with:
          path: .moon/cache
          key: ${{ runner.os }}-moon-${{ github.sha }}
          restore-keys: ${{ runner.os }}-moon-
      - run: moon ci :test :lint --base main
