name: CI Pipeline
run-name: "CI Run for change: ${{ github.event.head_commit.message }}"

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - run: moon ci :test :lint
      
        
      
